import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import { CartProvider } from "./context/CartContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Header />
        <CartProvider>
          {children}
        </CartProvider>
      </body>
      
    </html>
  );
}
